@startuml
'https://plantuml.com/class-diagram

component controller
component service
component repository
component email
component domain

controller --> service : requires
service --> repository : requires
service --> email : requires

repository --> domain : requires

note right of service: exports service.doctor
note right of repository: exports dao.doctor
note right of email: exports mailservice
note right of domain: exports model.doctor


@enduml